export const Categories = [
  "Sexual assault",
  "Threatening",
  "Child Sexual Abuse",
  "Marital rape",
  "Incest(sexual intrusion between family members)",
  "Sexual Exploitaion By Professionals",
  "Body shaming",
  "Threats to publish nude photo's",
  "Stalking",
  "Pornographic images to threaten",
  "Forcing to take part in pornography",
  "Following or Tracking",
  "Threatening to commit suicide",
  "Forcing into prostitution",
  "Sexual touching",
  "Cyberstalking",
  "Trolling",
  "Insulting",
  "Hidden Cameras",
  "Touching in any way you doesn't want",
  "Forcing into sexual acts",
  "Slapping, Beating, Punching, Kicking, Burning, Stabbing",
  "keeping you imprisoned",
  "Sexual Violence Within Prisons",
  "Same Gender Assault",
  "Gang Rape",
  "Destroying immigration papers",
  "Not letting you to see your friends or family",
  "Others",
];
